### ISSUE TITLE
1.2.0 TODO

### ISSUE THREAD

**Issue by stqism** [KittyHawkIrc/core#8]
## Features
- [x] mod_update
- [x] Encoder support
- [x] Flood protection
- [x] Bot invites
- [x] Save state changes to config
- [x] Sync support in config
- [X] Nickname support
- [x] Persist locker box
## Bugs
- [x] Auto-rejoin is broken
- [x] Unable to load unique config paths
- [x] kgb.conf poorly documented
