### ISSUE TITLE
1.3.0 TODO

### ISSUE THREAD

**Issue by stqism** [KittyHawkIrc/core#9]
## Features
- [ ] Heatbeat daemon
- [ ] Periodically save persisting lockers
- [x] Better command listing
- [X] Config API
- [X] Config management
- [ ] Protocol agnostic SQLish connectors
- [ ] Per channel hooks
- [ ] String formatting for commands
## Bugs
- [ ] Unable to detect disconnections
- [ ] Hook commands not displayed during help
